macro(vsg_copy_imgui_headers)
    set(options)
    set(oneValueArgs )
    set(multiValueArgs FILES)
    cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    file(MAKE_DIRECTORY ${VSGIMGUI_BINARY_DIR}/include/vsgImGui)

    foreach(FILE_TO_COPY ${ARGS_FILES})
        get_filename_component(FILENAME ${FILE_TO_COPY} NAME)
        set(OUTPUT_FILE ${VSGIMGUI_BINARY_DIR}/include/vsgImGui/${FILENAME})
        configure_file(${FILE_TO_COPY} ${OUTPUT_FILE} COPYONLY)
        list(APPEND VSGIMGUI_GENERATED_HEADERS ${OUTPUT_FILE})
    endforeach()
endmacro()

macro(vsg_create_dependency_header FILENAME INCLUDE_NAME)
    file(MAKE_DIRECTORY ${VSGIMGUI_BINARY_DIR}/include/vsgImGui)
    set(OUTPUT_FILE ${VSGIMGUI_BINARY_DIR}/include/vsgImGui/${FILENAME})
    file(WRITE ${OUTPUT_FILE} "#pragma once\n#include <${INCLUDE_NAME}>\n")
    list(APPEND VSGIMGUI_GENERATED_HEADERS ${OUTPUT_FILE})
endmacro()
